### ISSUE TITLE
Make web3 an optional dependency

### ISSUE THREAD

**Issue by sebastianst** [rkalis/truffle-assertions#22]
I use `truffle-assertions` in a typescript truffle project and it works great. However, it is currently the only package that explicitly adds `web3` as a dependency. Without it, my dependency tree would be much smaller. It is usually not needed as it is provided by a global truffle installation. I was wondering if you could make `web3` an optional dependency?

**Comment by rkalis** [comment]
Hi @sebastianst. Thanks for raising this issue. I'd been thinking about this myself as well, as I'd rather get rid of the dependency altogether, but I'd been postponing it. I think that the explicit dependency is kind of unnecessary, since most people are using the library together with truffle, which already injects web3. I'll look at this later this week.

For a later release I want to change the `createTransactionResult` method to completely remove all dependency on web3, explicit or implicit. But that's separate from this issue.

**Comment by rkalis** [comment]
By the way, since you mentioned you're using the library in a TS project, how is that working for you? Do you write your tests in TS as well then, and are you missing typings when using `truffle-assertions`?

I wanted to add typings for the different functions in the library, but never got to it, since most people I spoke with were writing their tests in JS, even when the project itself was in TS.

**Comment by sebastianst** [comment]
Sounds good to remove the web3 dep for `createTransactionResult`.

Yes, I use TS for writing tests and it has been very painful so far, as web3 is currently upgrading to v1 and constantly changing the API. Types from the `web3` module's `types` folder sometimes differ wildly to those of `@types/web3` and are incompatible at times. E.g. you have to import/declare the `Web3` class in two different ways, depending on what types you use, see [this PR](https://github.com/ethereum-ts/truffle-typings/pull/7) where I give the two ways in which types have to be declared for `truffle-typings`. I also sometimes have to resort to `(web3.foo as any)...` because the typings are so inconsistent at the moment.

Then there's the issue that there are two different modules for big numbers in use, which are responsible for [quite some confusion in truffle](https://github.com/ethereum-ts/TypeChain/issues/136) at the moment, further complicating typing for `bn.js`'s `BN` class (which is called `BigNumber` in `web3-utils` even though `BigNumber` usually refers to the main class of `bignumber.js`...).

Anyway, we can work together on clean types for `truffle-assertions` if you're interested.

**Comment by rkalis** [comment]
Thanks again for raising the issue. I removed the dependency, so the library now fully expects an existing web3 instance to be available, which I think is fine, since it is meant to be used together with truffle. I also added an additional note to the docs of the `createTransactionResult` function regarding this. This is published in truffle-assertions@0.8.0

**Comment by rkalis** [comment]
Sounds like there's a lack of good TypeScript functionality in the current web3 ecosystem, and the ever-changing APIs definitely don't help, I can relate to your problems.

If you're up for it I am definitely open to any PRs regarding typings for `truffle-assertions`!
