### ISSUE TITLE
Make "reverts" automatically unpack promises?

### ISSUE THREAD

**Issue by JimLynchCodes** [rkalis/truffle-assertions#37]
**Is your feature request related to a problem?**

I was writing some tests, and I had forgotten to await the reverts function itself...

Here's the correct syntax:
```
await truffleAssert.reverts(ownerStorage.getCount.call(accounts[0], { from: accounts[1] }));
```

I was just writing the function like this:
``` 
truffleAssert.reverts(ownerStorage.getCount.call(accounts[0], { from: accounts[1] }));
```

The problem is that in the second way the function _always passes._

It doesn't make a big explosion or fail- instead is passes fine even when the source code does not revert, which is pretty dangerous imo because now your tests are no longer reliably telling you that everything works.

**Describe the solution you'd like**

Either some kind of compiler error (only when passing in a promise) or syntax hi-lighter warning or something to let people know, "hey, you need to await truffleAssert.reverts in order for it to be doing what you think it's doing".

**Comment by rkalis** [comment]
I agree that would be helpful. I don't think it's possible to provide this kind of type-hint on truffle-assertions specifically, since it's a general issue with JavaScript that it generally doesn't tell you that you still need to await a promise.

One thing I can do though is either adding some JSDoc comments with typing information or converting the repo to TypeScript. This should convey better typing information to editors, so they can give you some linter message about it.

I'll close this issue and open another one specifically for this.
